//CREATE NEW ATTRIBUTE "idx" FOR EACH OBJECT IN THE SCENE

//scene generic
var scene = {"dictNodes":{"0":{"actionTarget":"Background","actionName":"","name":null,"next":"330","tru":"True","idx":"0","posX":"1.740251","posY":"6.925503","minimized":"False","advance_mode":"OnClick","type":"action"},"330":{"content":"It's a fine Spring morning in the town of Wildville. Two fellas, Average Jane and Average Joe wake to start the day. ","owner":null,"speaking":"True","name":"Dialogue State","next":"332","tru":"True","idx":"330","posX":"5.013221","posY":"7.08413","minimized":"False","advance_mode":"OnClick","type":"dialogue"},"332":{"choiceType":"object","content":"Who would you like to follow today?","owner":"","speaking":"False","prompted":"True","choices":"334~~Average Joe ~~False~~male_5~~true~-~335~~Average Jane~~False~~female_19~~true~-~","variable":null,"name":null,"next":"-1","tru":"True","idx":"332","posX":"8.428686","posY":"4.248403","minimized":"False","advance_mode":"OnClick","type":"choice"},"334":{"displayName":null,"owner":"{ObjectChoice}","newValue":"1","fromVariable":"False","get":"True","name":"Variable Sticker","next":"23085","tru":"True","idx":"334","posX":"12.24389","posY":"7.960137","minimized":"False","advance_mode":"OnClick","type":"variable"},"335":{"displayName":null,"owner":"{objectchoice}","newValue":"1","fromVariable":"False","get":"True","name":"Variable Sticker","next":"23084","tru":"True","idx":"335","posX":"12.33036","posY":"1.500647","minimized":"False","advance_mode":"OnClick","type":"variable"},"23082":{"actionTarget":"female_19","actionName":"Flip","action_vertical":"False","action_horizontal":"True","name":null,"next":"23083","tru":"True","idx":"23082","posX":"19.54249","posY":"-0.08288383","minimized":"False","advance_mode":"WhenCompleted","type":"action"},"23083":{"actionTarget":"female_19","actionName":"MoveTo","action_x-position":"-550","action_y-position":"-50.44","action_time":"2","action_easing":"ease_in_out_quad","name":null,"next":"23087","tru":"True","idx":"23083","posX":"23.11125","posY":"-1.148496","minimized":"False","advance_mode":"OnClick","type":"action"},"23084":{"content":"Average Jane it is! Let's go!","owner":null,"speaking":"True","name":"Dialogue State","next":"23082","tru":"True","idx":"23084","posX":"15.86719","posY":"1.27937","minimized":"False","advance_mode":"OnClick","type":"dialogue"},"23085":{"content":"Average Joe it is! Let's go! ","owner":null,"speaking":"True","name":"Dialogue State","next":"23086","tru":"True","idx":"23085","posX":"15.57181","posY":"7.496851","minimized":"False","advance_mode":"OnClick","type":"dialogue"},"23086":{"actionTarget":"male_5","actionName":"MoveTo","action_x-position":"550","action_y-position":"-59.76","action_time":"2","action_easing":"ease_in_out_quad","name":null,"next":"23088","tru":"True","idx":"23086","posX":"19.22672","posY":"5.834739","minimized":"False","advance_mode":"OnClick","type":"action"},"23087":{"nextScript":"Scene 2","transitionText":"","variablePairs":"","name":"End Sticker","next":"-1","tru":"True","idx":"23087","posX":"26.71502","posY":"0.4201695","minimized":"False","advance_mode":"OnClick","type":"end"},"23088":{"nextScript":"Scene 2 copy 1","transitionText":"None","variablePairs":"","name":"End Sticker","next":"-1","tru":"True","idx":"23088","posX":"25.44522","posY":"7.292221","minimized":"False","advance_mode":"OnClick","type":"end"}},"scene":{"name":"Scene 1","title":"Scene 1","pos":{"x":0,"y":0,"z":0},"uid":"0","background":"rooftop_2","furniture":[{"uid":0,"rotation":0,"visible":true,"locked":true,"color":"FFFFFF","textcolor":"000000","image":"rooftop_2","value":0,"text":"","fontSize":0,"parentName":"","objectType":0,"name":"Background","pos":{"x":0,"y":0,"z":0},"size":{"x":960,"y":540}},{"uid":1,"rotation":0,"visible":true,"locked":false,"color":"FFFFFF","textcolor":"000000","image":"female_19","value":0,"text":"","fontSize":0,"parentName":"","objectType":0,"name":"female_19","pos":{"x":-201.769928,"y":-50.442482,"z":0},"size":{"x":78,"y":285}},{"uid":2,"rotation":0,"visible":true,"locked":false,"color":"FFFFFF","textcolor":"000000","image":"male_5","value":0,"text":"","fontSize":0,"parentName":"","objectType":0,"name":"male_5","pos":{"x":130.800018,"y":-47.9999962,"z":0},"size":{"x":70,"y":273}}],"layoutScale":0.5,"layoutPosition":{"x":0,"y":0},"scriptorScale":0.5020931,"scriptorPosition":{"x":-1044.13281,"y":-202.460373},"layoutParamSet":true,"scriptorParamSet":true},"started":false}

//scene covid
// var scene = {
//   "dictNodes": {
//     "0": {
//       "actionTarget": null,
//       "actionName": "",
//       "name": null,
//       "next": "3",
//       "tru": "True",
//       "idx": "0",
//       "posX": "-0.1000638",
//       "posY": "14.17315",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "action"
//     },
//     "3": {
//       "content": "I know many people are staying at home because of “COVID-19” or “Coronavirus,” but how much do you know about it?",
//       "owner": "Doc",
//       "speaking": "True",
//       "name": "Dialogue State",
//       "next": "38",
//       "tru": "True",
//       "idx": "3",
//       "posX": "2.93589",
//       "posY": "14.17701",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "dialogue"
//     },
//     "33": {
//       "nextScript": "01_prevention.json",
//       "transitionText": "None",
//       "variablePairs": "",
//       "name": "End Sticker",
//       "next": "-1",
//       "tru": "True",
//       "idx": "33",
//       "posX": "102.2538",
//       "posY": "10.16475",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "end"
//     },
//     "38": {
//       "content": "Why not answer these six questions? It can help you know better about the Coronavirus!",
//       "owner": "Doc",
//       "speaking": "True",
//       "name": "Dialogue State",
//       "next": "39",
//       "tru": "True",
//       "idx": "38",
//       "posX": "5.87502",
//       "posY": "14.2214",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "dialogue"
//     },
//     "39": {
//       "choiceType": "simple",
//       "content": "Q1: Coronavirus has this name is because ",
//       "owner": "Doc",
//       "speaking": "True",
//       "prompted": "True",
//       "choices": "83~~It’s from Corona beer.~~True~~none~~true~-~85~~The virus has a corona shape.~~True~~none~~true~-~",
//       "variable": null,
//       "name": null,
//       "next": "-1",
//       "tru": "True",
//       "idx": "39",
//       "posX": "9.060729",
//       "posY": "14.28118",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "choice"
//     },
//     "40": {
//       "content": "Nope. It has nothing to do with the beer. You won’t get it when drinking Corona beer.",
//       "owner": "Doc",
//       "speaking": "True",
//       "name": "Dialogue State",
//       "next": "84",
//       "tru": "True",
//       "idx": "40",
//       "posX": "12.79525",
//       "posY": "12.38513",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "dialogue"
//     },
//     "41": {
//       "displayName": null,
//       "owner": "{CorrectCount}",
//       "newValue": "{CorrectCount}+1",
//       "fromVariable": "False",
//       "get": "True",
//       "name": "Variable Sticker",
//       "next": "84",
//       "tru": "True",
//       "idx": "41",
//       "posX": "16.13185",
//       "posY": "9.183406",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "variable"
//     },
//     "42": {
//       "content": "Yes. It has a corona shape, so it got this name. Specifically, it’s just one of many corona virus we know, so “COVID-19” is a more specific name.",
//       "owner": "Doc",
//       "speaking": "True",
//       "name": "Dialogue State",
//       "next": "41",
//       "tru": "True",
//       "idx": "42",
//       "posX": "12.78388",
//       "posY": "9.183386",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "dialogue"
//     },
//     "43": {
//       "choiceType": "simple",
//       "content": "Q2: Young adults do not need to worry about Coronavirus. Is this right?",
//       "owner": "Doc",
//       "speaking": "True",
//       "prompted": "True",
//       "choices": "47~~Yes, only babies and old people need to worry.~~True~~none~~true~-~46~~No, there’s still a chance.~~True~~none~~true~-~",
//       "variable": null,
//       "name": null,
//       "next": "-1",
//       "tru": "True",
//       "idx": "43",
//       "posX": "19.70096",
//       "posY": "14.13676",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "choice"
//     },
//     "45": {
//       "displayName": null,
//       "owner": "{CorrectCount}",
//       "newValue": "{CorrectCount}+1",
//       "fromVariable": "False",
//       "get": "True",
//       "name": "Variable Sticker",
//       "next": "87",
//       "tru": "True",
//       "idx": "45",
//       "posX": "25.36836",
//       "posY": "8.967388",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "variable"
//     },
//     "46": {
//       "content": "Yes, everyone should take care of it.",
//       "owner": "Doc",
//       "speaking": "True",
//       "name": "Dialogue State",
//       "next": "45",
//       "tru": "True",
//       "idx": "46",
//       "posX": "22.57436",
//       "posY": "9.569733",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "dialogue"
//     },
//     "47": {
//       "content": "Nope. Young adults have a relatively low chance being infected, but it’s not zero.",
//       "owner": "Doc",
//       "speaking": "True",
//       "name": "Dialogue State",
//       "next": "87",
//       "tru": "True",
//       "idx": "47",
//       "posX": "22.70798",
//       "posY": "12.58939",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "dialogue"
//     },
//     "48": {
//       "displayName": null,
//       "owner": "{CorrectCount}",
//       "newValue": "{CorrectCount}+1",
//       "fromVariable": "False",
//       "get": "True",
//       "name": "Variable Sticker",
//       "next": "49",
//       "tru": "True",
//       "idx": "48",
//       "posX": "32.97856",
//       "posY": "12.79808",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "variable"
//     },
//     "49": {
//       "content": "Coronavirus is contagious and has a higher fatality rate than common flu.",
//       "owner": "Doc",
//       "speaking": "True",
//       "name": "Dialogue State",
//       "next": "53",
//       "tru": "True",
//       "idx": "49",
//       "posX": "36.27192",
//       "posY": "8.046263",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "dialogue"
//     },
//     "51": {
//       "choiceType": "simple",
//       "content": "Q3: Coronavirus is more severe than a common flu. Is this correct?",
//       "owner": "Doc",
//       "speaking": "True",
//       "prompted": "True",
//       "choices": "48~~Yes, it’s much serious.~~True~~none~~true~-~49~~No, it’s just a flu.~~True~~none~~true~-~",
//       "variable": null,
//       "name": null,
//       "next": "-1",
//       "tru": "True",
//       "idx": "51",
//       "posX": "29.70454",
//       "posY": "13.8197",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "choice"
//     },
//     "53": {
//       "choiceType": "simple",
//       "content": "Q4: Which of the following is not the most common symptom of COVID-19?",
//       "owner": "Doc",
//       "speaking": "True",
//       "prompted": "True",
//       "choices": "54~~Fever~~True~~none~~true~-~54~~Shortness of Breath ~~True~~none~~true~-~54~~Dry cough~~True~~none~~true~-~55~~Diarrhea~~True~~none~~true~-~",
//       "variable": null,
//       "name": null,
//       "next": "-1",
//       "tru": "True",
//       "idx": "53",
//       "posX": "40.30532",
//       "posY": "13.89941",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "choice"
//     },
//     "54": {
//       "content": "Oops, this is one of the most common symptoms: fever, dry cough, and short of breath. Diarrhea is not a common one.",
//       "owner": "Doc",
//       "speaking": "True",
//       "name": "Dialogue State",
//       "next": "57",
//       "tru": "True",
//       "idx": "54",
//       "posX": "45.63234",
//       "posY": "9.625874",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "dialogue"
//     },
//     "55": {
//       "content": "Yes, diarrhea is not one of the most common symptoms: fever, dry cough, and short of breath.",
//       "owner": "Doc",
//       "speaking": "True",
//       "name": "Dialogue State",
//       "next": "56",
//       "tru": "True",
//       "idx": "55",
//       "posX": "45.6183",
//       "posY": "5.862619",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "dialogue"
//     },
//     "56": {
//       "displayName": null,
//       "owner": "{CorrectCount}",
//       "newValue": "{CorrectCount}+1",
//       "fromVariable": "False",
//       "get": "True",
//       "name": "Variable Sticker",
//       "next": "57",
//       "tru": "True",
//       "idx": "56",
//       "posX": "48.72876",
//       "posY": "5.864494",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "variable"
//     },
//     "57": {
//       "choiceType": "simple",
//       "content": "Q5: Coronavirus cannot spread in the following way:",
//       "owner": "Doc",
//       "speaking": "True",
//       "prompted": "True",
//       "choices": "58~~Small droplets from the nose or mouth~~True~~none~~true~-~59~~Eye contact~~True~~none~~true~-~58~~Touch your face after touching surfaces with Coronavirus.~~True~~none~~true~-~",
//       "variable": null,
//       "name": null,
//       "next": "-1",
//       "tru": "True",
//       "idx": "57",
//       "posX": "52.44117",
//       "posY": "14.04424",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "choice"
//     },
//     "58": {
//       "content": "Umm… this may happen, actually.",
//       "owner": "Doc",
//       "speaking": "True",
//       "name": "Dialogue State",
//       "next": "61",
//       "tru": "True",
//       "idx": "58",
//       "posX": "55.99883",
//       "posY": "11.16057",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "dialogue"
//     },
//     "59": {
//       "content": "Easy, easy. It won’t kill you through eye contacts.",
//       "owner": "Doc",
//       "speaking": "True",
//       "name": "Dialogue State",
//       "next": "60",
//       "tru": "True",
//       "idx": "59",
//       "posX": "55.82767",
//       "posY": "8.25235",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "dialogue"
//     },
//     "60": {
//       "displayName": null,
//       "owner": "{CorrectCount}",
//       "newValue": "{CorrectCount}+1",
//       "fromVariable": "False",
//       "get": "True",
//       "name": "Variable Sticker",
//       "next": "61",
//       "tru": "True",
//       "idx": "60",
//       "posX": "58.96928",
//       "posY": "8.278996",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "variable"
//     },
//     "61": {
//       "content": "The disease can spread from person to person through small droplets from the nose or mouth which are spread when a person with COVID-19 coughs or exhales. ",
//       "owner": "Doc",
//       "speaking": "True",
//       "name": "Dialogue State",
//       "next": "62",
//       "tru": "True",
//       "idx": "61",
//       "posX": "62.51634",
//       "posY": "11.14714",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "dialogue"
//     },
//     "62": {
//       "content": "These droplets land on objects and surfaces around the person. Other people then catch COVID-19 by touching these objects or surfaces, then touching their eyes, nose or mouth.",
//       "owner": "Doc",
//       "speaking": "True",
//       "name": "Dialogue State",
//       "next": "63",
//       "tru": "True",
//       "idx": "62",
//       "posX": "65.5862",
//       "posY": "11.09512",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "dialogue"
//     },
//     "63": {
//       "choiceType": "simple",
//       "content": "Q6: If I have no symptoms, I don’t have Coronavirus.",
//       "owner": "Doc",
//       "speaking": "True",
//       "prompted": "True",
//       "choices": "64~~Of course!~~True~~none~~true~-~65~~Perhaps not.~~True~~none~~true~-~",
//       "variable": null,
//       "name": null,
//       "next": "-1",
//       "tru": "True",
//       "idx": "63",
//       "posX": "69.10794",
//       "posY": "12.95533",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "choice"
//     },
//     "64": {
//       "content": "Well, definitely I hope you are okay. But it’s possible you show mild or no symptoms. And don’t forget it has an incubation period varying from 1~14 days. ",
//       "owner": "Doc",
//       "speaking": "True",
//       "name": "Dialogue State",
//       "next": "67",
//       "tru": "True",
//       "idx": "64",
//       "posX": "72.22778",
//       "posY": "11.36375",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "dialogue"
//     },
//     "65": {
//       "content": "Yes, it’s possible you show mild or no symptoms. And don’t forget it has an incubation period varying from 1~14 days. ",
//       "owner": "Doc",
//       "speaking": "True",
//       "name": "Dialogue State",
//       "next": "66",
//       "tru": "True",
//       "idx": "65",
//       "posX": "72.25151",
//       "posY": "7.464516",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "dialogue"
//     },
//     "66": {
//       "displayName": null,
//       "owner": "{CorrectCount}",
//       "newValue": "{CorrectCount}+1",
//       "fromVariable": "False",
//       "get": "True",
//       "name": "Variable Sticker",
//       "next": "67",
//       "tru": "True",
//       "idx": "66",
//       "posX": "75.36217",
//       "posY": "7.401139",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "variable"
//     },
//     "67": {
//       "content": "Great! Let’s see… you answered {CorrectCount}/6 questions correctly. ",
//       "owner": "Doc",
//       "speaking": "True",
//       "name": "Dialogue State",
//       "next": "68",
//       "tru": "True",
//       "idx": "67",
//       "posX": "80.02599",
//       "posY": "11.42904",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "dialogue"
//     },
//     "68": {
//       "choices": "69~~{CorrectCount}>3~-~70~~true~-~",
//       "isRandom": "False",
//       "name": "If Sticker",
//       "next": "-1",
//       "tru": "True",
//       "idx": "68",
//       "posX": "83.18265",
//       "posY": "11.47659",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "if"
//     },
//     "69": {
//       "content": "Great job! It seems you know much about Coronavirus. Take care and protect yourself!",
//       "owner": "Doc",
//       "speaking": "True",
//       "name": "Dialogue State",
//       "next": "75",
//       "tru": "True",
//       "idx": "69",
//       "posX": "86.91051",
//       "posY": "11.43562",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "dialogue"
//     },
//     "70": {
//       "content": "Oh you need to know more about Coronavirus, you can play it again or know more from official websites.",
//       "owner": "Doc",
//       "speaking": "True",
//       "name": "Dialogue State",
//       "next": "75",
//       "tru": "True",
//       "idx": "70",
//       "posX": "87.0661",
//       "posY": "7.673068",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "dialogue"
//     },
//     "71": {
//       "content": "To know more information, click the button on the right to WHO (World Health Organization) and CDC (Centers for Disease Control and Prevention) website for more info. ",
//       "owner": "Doc",
//       "speaking": "True",
//       "name": "Dialogue State",
//       "next": "74",
//       "tru": "True",
//       "idx": "71",
//       "posX": "95.77853",
//       "posY": "10.20973",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "dialogue"
//     },
//     "74": {
//       "content": "Thanks for playing!",
//       "owner": "Doc",
//       "speaking": "True",
//       "name": "Dialogue State",
//       "next": "33",
//       "tru": "True",
//       "idx": "74",
//       "posX": "98.98217",
//       "posY": "10.1483",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "dialogue"
//     },
//     "75": {
//       "actionTarget": "CDC link",
//       "actionName": "Visibility",
//       "action_hidden": "False",
//       "name": null,
//       "next": "77",
//       "tru": "True",
//       "idx": "75",
//       "posX": "90.17825",
//       "posY": "9.633665",
//       "minimized": "False",
//       "advance_mode": "Instantly",
//       "type": "action"
//     },
//     "77": {
//       "actionTarget": "CDC link",
//       "actionName": "Visibility",
//       "action_hidden": "False",
//       "name": null,
//       "next": "71",
//       "tru": "True",
//       "idx": "77",
//       "posX": "92.96328",
//       "posY": "10.0474",
//       "minimized": "False",
//       "advance_mode": "Instantly",
//       "type": "action"
//     },
//     "78": {
//       "customEventName": "",
//       "eventDetails": "CDC link",
//       "startsActive": "True",
//       "takesFocus": "False",
//       "eventType": "ObjectClick",
//       "name": "Event State",
//       "next": "79",
//       "tru": "True",
//       "idx": "78",
//       "posX": "1.500842",
//       "posY": "4.241108",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "event"
//     },
//     "79": {
//       "functionType": "LinkToURL",
//       "functionDetail": "https://www.cdc.gov/coronavirus/2019-nCoV/idx.html",
//       "functionDetail2": "",
//       "functionDetail3": "",
//       "functionDetail4": "",
//       "functionDetail5": "",
//       "name": "Call Function State",
//       "next": "-1",
//       "tru": "True",
//       "idx": "79",
//       "posX": "4.932432",
//       "posY": "4.059969",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "callfunction"
//     },
//     "80": {
//       "customEventName": "",
//       "eventDetails": "WHO link",
//       "startsActive": "True",
//       "takesFocus": "False",
//       "eventType": "ObjectClick",
//       "name": "Event State",
//       "next": "81",
//       "tru": "True",
//       "idx": "80",
//       "posX": "1.491981",
//       "posY": "0.7296549",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "event"
//     },
//     "81": {
//       "functionType": "LinkToURL",
//       "functionDetail": "https://www.who.int/docs/default-source/coronaviruse/situation-reports/20200318-sitrep-58-covid-19.pdf",
//       "functionDetail2": "",
//       "functionDetail3": "",
//       "functionDetail4": "",
//       "functionDetail5": "",
//       "name": "Call Function State",
//       "next": "-1",
//       "tru": "True",
//       "idx": "81",
//       "posX": "4.923569",
//       "posY": "0.548516",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "callfunction"
//     },
//     "83": {
//       "actionTarget": "SARS-CoV-2_without_background",
//       "actionName": "Visibility",
//       "action_hidden": "False",
//       "name": null,
//       "next": "40",
//       "tru": "True",
//       "idx": "83",
//       "posX": "12.37091",
//       "posY": "17.89678",
//       "minimized": "False",
//       "advance_mode": "Instantly",
//       "type": "action"
//     },
//     "84": {
//       "actionTarget": "SARS-CoV-2_without_background",
//       "actionName": "Visibility",
//       "action_hidden": "True",
//       "name": null,
//       "next": "43",
//       "tru": "True",
//       "idx": "84",
//       "posX": "16.70798",
//       "posY": "17.96068",
//       "minimized": "False",
//       "advance_mode": "Instantly",
//       "type": "action"
//     },
//     "85": {
//       "actionTarget": "SARS-CoV-2_without_background",
//       "actionName": "Visibility",
//       "action_hidden": "False",
//       "name": null,
//       "next": "42",
//       "tru": "True",
//       "idx": "85",
//       "posX": "9.289806",
//       "posY": "8.213298",
//       "minimized": "False",
//       "advance_mode": "Instantly",
//       "type": "action"
//     },
//     "87": {
//       "content": "And don't forget, even though you don't have simptoms, you may still infect others. Be considerate!",
//       "owner": "Doc",
//       "speaking": "True",
//       "name": "Dialogue State",
//       "next": "88",
//       "tru": "True",
//       "idx": "87",
//       "posX": "25.69908",
//       "posY": "14.67883",
//       "minimized": "False",
//       "advance_mode": "OnClick",
//       "type": "dialogue"
//     },
//     "88": {
//       "actionTarget": "borna_child_asian_1",
//       "actionName": "Visibility",
//       "action_hidden": "False",
//       "name": null,
//       "next": "89",
//       "tru": "True",
//       "idx": "88",
//       "posX": "20.34543",
//       "posY": "25.21618",
//       "minimized": "False",
//       "advance_mode": "AfterTime_1",
//       "type": "action"
//     },
//     "89": {
//       "actionTarget": "SARS-CoV-2_without_background(1)",
//       "actionName": "MoveTo",
//       "action_y-position": "-18",
//       "action_x-position": "330",
//       "action_time": "2",
//       "action_easing": "ease_in_out_quad",
//       "name": null,
//       "next": "90",
//       "tru": "True",
//       "idx": "89",
//       "posX": "23.57882",
//       "posY": "24.24396",
//       "minimized": "False",
//       "advance_mode": "AfterTime_2",
//       "type": "action"
//     },
//     "90": {
//       "actionTarget": "borna_child_asian_1",
//       "actionName": "Visibility",
//       "action_hidden": "True",
//       "name": null,
//       "next": "51",
//       "tru": "True",
//       "idx": "90",
//       "posX": "26.9579",
//       "posY": "25.29501",
//       "minimized": "False",
//       "advance_mode": "AfterTime_1",
//       "type": "action"
//     }
//   },
//   "scene": {
//     "name": "Scene 1",
//     "title": "Whatis",
//     "pos": {
//       "x": 0.0,
//       "y": 0.0,
//       "z": 0.0
//     },
//     "uid": "1",
//     "background": "wall_inside_9",
//     "furniture": [
//       {
//         "uid": 0,
//         "rotation": 0.0,
//         "visible": true,
//         "locked": true,
//         "color": "FFFFFF",
//         "textcolor": "000000",
//         "image": "wall_inside_9",
//         "value": 0.0,
//         "text": "",
//         "fontSize": 0,
//         "parentName": "",
//         "objectType": 0,
//         "name": "Background",
//         "pos": {
//           "x": 0.0,
//           "y": 0.0,
//           "z": 0.0
//         },
//         "size": {
//           "x": 960.0,
//           "y": 540.0
//         }
//       },
//       {
//         "uid": 1,
//         "rotation": 0.0,
//         "visible": true,
//         "locked": false,
//         "color": "FFFFFF",
//         "textcolor": "000000",
//         "image": "lab_scientist_2",
//         "value": 0.0,
//         "text": "",
//         "fontSize": 0,
//         "parentName": "",
//         "objectType": 0,
//         "name": "Doc",
//         "pos": {
//           "x": -313.6141,
//           "y": -56.8612938,
//           "z": 0.0
//         },
//         "size": {
//           "x": 95.0,
//           "y": 310.0
//         }
//       },
//       {
//         "uid": 2,
//         "rotation": 0.0,
//         "visible": false,
//         "locked": false,
//         "color": "FFFFFF",
//         "textcolor": "000000",
//         "image": "board_3",
//         "value": 0.0,
//         "text": "",
//         "fontSize": 0,
//         "parentName": "",
//         "objectType": 0,
//         "name": "CDC link",
//         "pos": {
//           "x": 342.570343,
//           "y": 151.690521,
//           "z": 0.0
//         },
//         "size": {
//           "x": 242.266876,
//           "y": 147.507339
//         }
//       },
//       {
//         "uid": 3,
//         "rotation": 0.0,
//         "visible": true,
//         "locked": false,
//         "color": "FFFFFF00",
//         "textcolor": "000000",
//         "image": "Text",
//         "value": 0.0,
//         "text": "CDC Website",
//         "fontSize": 24,
//         "parentName": "CDC link",
//         "objectType": 2,
//         "name": "Text(1)",
//         "pos": {
//           "x": 89.31341,
//           "y": -37.8634033,
//           "z": 0.0
//         },
//         "size": {
//           "x": 310.942932,
//           "y": 100.0
//         }
//       },
//       {
//         "uid": 4,
//         "rotation": 0.0,
//         "visible": false,
//         "locked": false,
//         "color": "FFFFFF",
//         "textcolor": "000000",
//         "image": "board_3",
//         "value": 0.0,
//         "text": "",
//         "fontSize": 0,
//         "parentName": "",
//         "objectType": 0,
//         "name": "WHO link",
//         "pos": {
//           "x": 346.208923,
//           "y": -54.97828,
//           "z": 0.0
//         },
//         "size": {
//           "x": 226.487808,
//           "y": 137.9001
//         }
//       },
//       {
//         "uid": 5,
//         "rotation": 0.0,
//         "visible": true,
//         "locked": false,
//         "color": "FFFFFF00",
//         "textcolor": "000000",
//         "image": "Text",
//         "value": 0.0,
//         "text": "WHO Website",
//         "fontSize": 24,
//         "parentName": "WHO link",
//         "objectType": 2,
//         "name": "Text",
//         "pos": {
//           "x": 87.08552,
//           "y": -31.54287,
//           "z": 0.0
//         },
//         "size": {
//           "x": 310.942932,
//           "y": 100.0
//         }
//       },
//       {
//         "uid": 6,
//         "rotation": 0.0,
//         "visible": false,
//         "locked": false,
//         "color": "FFFFFF",
//         "textcolor": "000000",
//         "image": "SARS-CoV-2_without_background",
//         "value": 0.0,
//         "text": "",
//         "fontSize": 0,
//         "parentName": "",
//         "objectType": 0,
//         "name": "SARS-CoV-2_without_background",
//         "pos": {
//           "x": 289.116669,
//           "y": 94.76016,
//           "z": 0.0
//         },
//         "size": {
//           "x": 200.0,
//           "y": 201.0
//         }
//       },
//       {
//         "uid": 7,
//         "rotation": 0.0,
//         "visible": false,
//         "locked": false,
//         "color": "FFFFFF",
//         "textcolor": "000000",
//         "image": "borna_child_asian_1",
//         "value": 0.0,
//         "text": "",
//         "fontSize": 0,
//         "parentName": "",
//         "objectType": 0,
//         "name": "borna_child_asian_1",
//         "pos": {
//           "x": -57.4799576,
//           "y": -40.7911072,
//           "z": 0.0
//         },
//         "size": {
//           "x": 150.224472,
//           "y": 150.224472
//         }
//       },
//       {
//         "uid": 8,
//         "rotation": 0.0,
//         "visible": true,
//         "locked": false,
//         "color": "FFFFFF",
//         "textcolor": "000000",
//         "image": "borna_grandmother_1",
//         "value": 0.0,
//         "text": "",
//         "fontSize": 0,
//         "parentName": "borna_child_asian_1",
//         "objectType": 0,
//         "name": "borna_grandmother_1",
//         "pos": {
//           "x": 272.086182,
//           "y": -3.69350052,
//           "z": 0.0
//         },
//         "size": {
//           "x": 125.601364,
//           "y": 125.601364
//         }
//       },
//       {
//         "uid": 9,
//         "rotation": 0.0,
//         "visible": true,
//         "locked": false,
//         "color": "FFFFFF",
//         "textcolor": "000000",
//         "image": "SARS-CoV-2_without_background",
//         "value": 0.0,
//         "text": "",
//         "fontSize": 0,
//         "parentName": "borna_child_asian_1",
//         "objectType": 0,
//         "name": "SARS-CoV-2_without_background(1)",
//         "pos": {
//           "x": -1.66211319,
//           "y": 34.88587,
//           "z": 0.0
//         },
//         "size": {
//           "x": 45.24348,
//           "y": 45.4696922
//         }
//       }
//     ],
//     "layoutScale": 0.4177249,
//     "layoutPosition": {
//       "x": -14.817729,
//       "y": 9.582329
//     },
//     "scriptorScale": 0.355840772,
//     "scriptorPosition": {
//       "x": -2192.958,
//       "y": -382.2136
//     },
//     "layoutParamSet": true,
//     "scriptorParamSet": true
//   },
//   "started": false
// }

